name: Environment Variable Demo

on:
  workflow_dispatch:

env:
  APP_NAME: workflow-app

jobs:
  env-demo:
    runs-on: ubuntu-latest

    env:
      APP_NAME: job-app

    steps:
      - name: Step 1 - Print Job Variable
        run: |
          echo "APP_NAME = $APP_NAME"

      - name: Step 2 - Step Level Override
        env:
          APP_NAME: step-app
        run: |
          echo "APP_NAME = $APP_NAME"

      - name: Step 3 - Print Again
        run: |
          echo "APP_NAME = $APP_NAME"

      - name: Step 4 - Change Shell Variable
        run: |
          APP_NAME=temporary-shell
          echo "Inside this step = $APP_NAME"

      - name: Step 5 - Check Again
        run: |
          echo "APP_NAME = $APP_NAME"
       
        
