name: Django Project Setup

on:
  push:
    branches:
      - main

  pull_request:

  workflow_dispatch:

jobs:
  django-app-setup-job:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4 
        - uses: actions/setup-python@v5
          with:
            python-version: "3.12"
        - name: check python version
          run: python --version
        - name: check where python
          run: which python
        - run: which pip
        - name: Install Dependencies
          run: pip install -r requirements.txt
        - name: Django Check
          run: python manage.py check
        - name: Run Tests
          run: python manage.py test
        
