name: Django Project Setup

on:
  push:
    branches:
      - feature/vars-demo

  pull_request:

  workflow_dispatch:

jobs:
  django-app-vars-job:
    env:
      APP_NAME: vars-demoapp
    runs-on: ubuntu-latest
    steps:
      - name: echo gloabl name
        run: echo $APP_NAME 
      - name: over riding app name
        run: APP_NAME=new_name_1
      - name: trying new name again
        run: echo is name changed $APP_NAME
      
       
        
